import argparse
import csv
from pathlib import Path

import numpy as np
import onnxruntime as ort

from utils.legacy_feature import normalize_legacy_feature_array


def parse_args():
    parser = argparse.ArgumentParser(
        description="Batch speaker verification on ONNX from a pair manifest."
    )
    parser.add_argument(
        "--manifest",
        type=str,
        required=True,
        help="CSV manifest generated by prepare_rknn_eval_set.py.",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="checkpoints/resnet_v7_vox2ft_s1_latest_fixed.onnx",
        help="Path to the ONNX model.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=None,
        help="Optional cosine threshold for same-speaker decision. Leave unset to export scores only.",
    )
    parser.add_argument(
        "--base-dir",
        type=str,
        default=".",
        help="Base directory used to resolve relative feature paths in the manifest.",
    )
    parser.add_argument(
        "--save-results",
        type=str,
        default="results_onnx.csv",
        help="CSV path to save pairwise scores.",
    )
    return parser.parse_args()


def normalize_input(array):
    return normalize_legacy_feature_array(array)


def l2_normalize(x, axis=1, eps=1e-12):
    denom = np.linalg.norm(x, axis=axis, keepdims=True)
    denom = np.maximum(denom, eps)
    return x / denom


def run_embedding(session, input_name, feature_path, cache):
    feature_key = str(feature_path)
    if feature_key in cache:
        return cache[feature_key]

    features = normalize_input(np.load(feature_path))
    outputs = session.run(None, {input_name: features})
    if not outputs:
        raise RuntimeError(f"ONNX inference returned no outputs for {feature_path}")

    embedding = np.asarray(outputs[0], dtype=np.float32)
    embedding = l2_normalize(embedding, axis=1)
    embedding = embedding.mean(axis=0, keepdims=True)
    embedding = l2_normalize(embedding, axis=1)
    cache[feature_key] = embedding
    return embedding


def cosine_score(emb_a, emb_b):
    return float(np.sum(emb_a * emb_b, axis=1)[0])


def main():
    args = parse_args()
    manifest_path = Path(args.manifest)
    model_path = Path(args.model)
    base_dir = Path(args.base_dir)
    results_path = Path(args.save_results)

    if not manifest_path.is_file():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")
    if not model_path.is_file():
        raise FileNotFoundError(f"ONNX model not found: {model_path}")

    session = ort.InferenceSession(str(model_path), providers=["CPUExecutionProvider"])
    input_name = session.get_inputs()[0].name

    rows = []
    cache = {}
    tp = tn = fp = fn = 0
    with open(manifest_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for idx, row in enumerate(reader, start=1):
            feature_a = base_dir / row["feature_a"]
            feature_b = base_dir / row["feature_b"]
            label = int(row["label"])

            emb_a = run_embedding(session, input_name, feature_a, cache)
            emb_b = run_embedding(session, input_name, feature_b, cache)
            score = cosine_score(emb_a, emb_b)
            pred = ""
            if args.threshold is not None:
                pred = 1 if score >= args.threshold else 0

                if label == 1 and pred == 1:
                    tp += 1
                elif label == 0 and pred == 0:
                    tn += 1
                elif label == 0 and pred == 1:
                    fp += 1
                else:
                    fn += 1

            rows.append(
                {
                    "index": idx,
                    "label": label,
                    "pred": pred,
                    "score": f"{score:.6f}",
                    "speaker_key": row["speaker_key"],
                    "feature_a": row["feature_a"],
                    "feature_b": row["feature_b"],
                }
            )
            if args.threshold is None:
                print(
                    f"[{idx}] label={label} score={score:.6f} "
                    f"{row['feature_a']} vs {row['feature_b']}"
                )
            else:
                print(
                    f"[{idx}] label={label} pred={pred} score={score:.6f} "
                    f"{row['feature_a']} vs {row['feature_b']}"
                )

    results_path.parent.mkdir(parents=True, exist_ok=True)
    with open(results_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "index",
                "label",
                "pred",
                "score",
                "speaker_key",
                "feature_a",
                "feature_b",
            ],
        )
        writer.writeheader()
        writer.writerows(rows)

    total = len(rows)
    print(f"Pairs: {total}")
    print(f"Unique features embedded: {len(cache)}")
    if args.threshold is None:
        print("Threshold: <unset>")
        print("Decision metrics: skipped (scores only)")
    else:
        accuracy = (tp + tn) / total if total else 0.0
        print(f"TP={tp} TN={tn} FP={fp} FN={fn}")
        print(f"Accuracy: {accuracy:.4f}")
        print(f"Threshold: {args.threshold:.6f}")
    print(f"Results: {results_path}")


if __name__ == "__main__":
    main()
