import argparse
import csv
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Sweep the best cosine threshold from a batch verification CSV."
    )
    parser.add_argument(
        "--results",
        type=str,
        required=True,
        help="Path to results.csv generated by rknn_batch_verify.py.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    results_path = Path(args.results)
    if not results_path.is_file():
        raise FileNotFoundError(f"Results file not found: {results_path}")

    rows = []
    with open(results_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append((int(row["label"]), float(row["score"])))

    if not rows:
        raise RuntimeError("No rows found in results file.")

    thresholds = sorted(set(score for _, score in rows))
    best = None
    for threshold in thresholds:
        tp = tn = fp = fn = 0
        for label, score in rows:
            pred = 1 if score >= threshold else 0
            if label == 1 and pred == 1:
                tp += 1
            elif label == 0 and pred == 0:
                tn += 1
            elif label == 0 and pred == 1:
                fp += 1
            else:
                fn += 1
        accuracy = (tp + tn) / len(rows)
        if best is None or accuracy > best["accuracy"]:
            best = {
                "accuracy": accuracy,
                "threshold": threshold,
                "tp": tp,
                "tn": tn,
                "fp": fp,
                "fn": fn,
            }

    same_scores = [score for label, score in rows if label == 1]
    diff_scores = [score for label, score in rows if label == 0]
    print(f"Pairs: {len(rows)}")
    print(f"same min/max: {min(same_scores):.6f} / {max(same_scores):.6f}")
    print(f"diff min/max: {min(diff_scores):.6f} / {max(diff_scores):.6f}")
    print(f"Best threshold: {best['threshold']:.6f}")
    print(f"Best accuracy: {best['accuracy']:.6f}")
    print(
        f"TP={best['tp']} TN={best['tn']} FP={best['fp']} FN={best['fn']}"
    )


if __name__ == "__main__":
    main()
